### ISSUE TITLE
Create templates for front page

### ISSUE THREAD

**Issue by RoySegall** [DrupalHub/drupalhub#27]
Let start create the templates of the views in the front page and then start work on them.
- [x] #6 (Create modal for new question)
- [x] #7 (Hot topics + front page question)
- [x] #10 (Recommendations for service providers)
- [x] #11 (Drupal of the month)
