### ISSUE TITLE
Theeming

### ISSUE THREAD

**Issue by Drupily** [DrupalHub/drupalhub#44]
sass , main file at drupalhub/drupalhub/themes/drupalhub/css/style.scss .
standards/procedures: 
1. file for each page type, remember to name it as partial ( _ at beginning of filename ) 
2. vars and mixins at style.scss .
3. remember to watch the file, to check all new files are committed  be4 push.
- [x] Font page themeing (#45)
- [ ] New question theming (#46)
- [x] Question page (#47)
- [x] Blog page themeing (#48)
- [ ] Group page themeing (#49)
- [ ] Theme youtube (#50)
- [ ] Youtube page (#53)
- [x] Adding strips on the top with menu (#56)
- [x] Work on fix the look on iPhone (#54)
- [ ] Front page service providers (#57) 
- [x] Login page #63
